17-01-2023 15:00:04 - psicologo-bergamo.net - ERROR - check_MD - 167 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 156, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
