13-01-2023 17:22:39 - www.studiocimagliagualtieri.it - ERROR - check_MD - 154 - Exception occurred
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Visibility\CheckWidget\WidgetChecker.py", line 143, in check_MD
    self.outcome.allows_booking = MappingIndividual(url = self.md[0]['href']).mapping.value
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
